services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads
    environment:
      - ENV=development
      - PORT=8080
      - GOOGLE_APPLICATION_CREDENTIALS=/app/credentials/firebase-service-account.json
    working_dir: /app
    networks:
      - armorum_network

  frontend:
    build: 
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8080
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - backend
    networks:
      - armorum_network

volumes:
  backend_uploads:

networks:
  armorum_network:
    driver: bridge
